PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?person foaf:name ?name .
    ?person foaf:position ?position .
    OPTIONAL { ?person foaf:mbox ?email } .
    FILTER (?position / 2 > 1023 / 2)
}
ORDER BY ?name






