PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
SELECT ?gname1 ?gname2
WHERE {
    { ?x foaf:name ?gname1 } 
    UNION { ?x foaf:position   ?gname2 } .
    FILTER REGEX(?gname1, "^da", "i")
}
ORDER BY ?gname1






