PREFIX vCard: <http://www.w3.org/2001/vcard-rdf/3.0#>

SELECT DISTINCT ?name
FROM <test/data/1.rdf>
WHERE {
    ?x vCard:FN  ?name .
};

SELECT DISTINCT ?name
FROM <test/data/1.rdf>
WHERE {
    ?x vCard:FN  ?name .
}
LIMIT 1
OFFSET 1
;